(define-module (home-observe plenticore)
  #:use-module (dbi dbi)
  #:use-module (gcrypt base64)
  #:use-module (gcrypt hash)
  #:use-module (gcrypt mac)
  #:use-module (gcrypt random)
  #:use-module (home-observe aes)
  #:use-module (ice-9 match)
  #:use-module (json)
  #:use-module (rnrs bytevectors)
  #:use-module ((scheme base) #:select (bytevector-append))
  #:use-module (web client)
  #:use-module (web response)
  #:use-module (web uri)
  #:export (observe))

(define *host* "plenticore.fritz.box")
(define *login-start* "/api/v2/auth/start")
(define *login-finish* "/api/v2/auth/finish")
(define *create-session* "/api/v2/auth/create_session")
(define *processdata* "/api/v2/processdata")

(define (scram-nonce n)
  (u8-list->bytevector (map (lambda (_) (random 256)) (iota n))))

(define (ensure-string o)
  (if (bytevector? o)
    (utf8->string o)
    o))

(define (bytevector-xor a b)
  (u8-list->bytevector (map logxor (bytevector->u8-list a) (bytevector->u8-list b))))

(define (pbkdf2 pwd salt rounds)
  (let loop ((i rounds)
             (up (bytevector-append salt (u8-list->bytevector '(0 0 0 1))))
             (res #f))
    (if (= i 0)
      res
      (let ((ui (sign-data pwd up #:algorithm (mac-algorithm hmac-sha256))))
        (loop (1- i) ui (if res
                          (bytevector-xor res ui)
                          ui))))))

(define (auth-start client-nonce)
  (call-with-values (lambda ()
                    (http-post (build-uri 'http #:host *host* #:path *login-start*)
                               #:headers '((content-type application/json (charset . "utf-8"))
                                           (accept (application/json))
                                           (accept-encoding (1000 . "gzip") (1000 . "deflate")))
                               #:body (scm->json-string `(("username" . "user")
                                                          ("nonce" . ,client-nonce)))))
  (lambda (res body)
    (json-string->scm (ensure-string body)))))

(define (auth-finish client-proof transaction-id)
  (call-with-values (lambda ()
                      (http-post (build-uri 'http #:host *host* #:path *login-finish*)
                                 #:headers '((content-type application/json (charset . "utf-8"))
                                             (accept (application/json))
                                             (accept-encoding (1000 . "gzip") (1000 . "deflate")))
                                 #:body (scm->json-string `(("proof" . ,(base64-encode client-proof))
                                                            ("transactionId" . ,(base64-encode transaction-id))))))
    (lambda (res body)
      (json-string->scm (ensure-string body)))))

(define (create-session session-nonce transaction-id cipher-text auth-tag)
  (call-with-values (lambda ()
                      (http-post (build-uri 'http #:host *host* #:path *create-session*)
                                 #:headers '((content-type application/json (charset . "utf-8"))
                                             (accept (application/json))
                                             (accept-encoding (1000 . "gzip") (1000 . "deflate")))
                                 #:body (scm->json-string `(("iv" . ,(base64-encode session-nonce))
                                                            ("tag" . ,(base64-encode auth-tag))
                                                            ("transactionId" . ,(base64-encode transaction-id))
                                                            ("payload" . ,(base64-encode cipher-text))))))
    (lambda (res body)
      (json-string->scm (ensure-string body)))))

(define (with-rfc5802-auth pwd thunk)
  (let ((token #f))
    (dynamic-wind
      (lambda ()
        (let* ((client-nonce (base64-encode (scram-nonce 16)))

               (srv-start (auth-start client-nonce))
               (rounds (assoc-ref srv-start "rounds"))
               (salt (base64-decode (assoc-ref srv-start "salt")))
               (server-nonce (base64-decode (assoc-ref srv-start "nonce")))
               (transaction-id (base64-decode (assoc-ref srv-start "transactionId")))
               (salted-pwd (pbkdf2 pwd salt rounds))
               (client-key (sign-data salted-pwd "Client Key" #:algorithm (mac-algorithm hmac-sha256)))
               (stored-key (sha256 client-key))
               (auth-msg (format #f "n=user,r=~a,r=~a,s=~a,i=~a,c=biws,r=~a"
                                 client-nonce
                                 (base64-encode server-nonce)
                                 (base64-encode salt)
                                 rounds
                                 (base64-encode server-nonce)))
               (client-signature (sign-data stored-key auth-msg #:algorithm (mac-algorithm hmac-sha256)))
               (client-proof (bytevector-xor client-key client-signature))
               (server-key (sign-data salted-pwd "Server Key" #:algorithm (mac-algorithm hmac-sha256)))
               (server-signature (sign-data server-key auth-msg #:algorithm (mac-algorithm hmac-sha256)))

               (srv-finish (auth-finish client-proof transaction-id))
               (session-token (string->utf8 (assoc-ref srv-finish "token")))
               (signature (base64-decode (assoc-ref srv-finish "signature")))
               (session-key (if (equal? signature server-signature)
                              (sign-data stored-key (bytevector-append (string->utf8 "Session Key") (string->utf8 auth-msg) client-key) #:algorithm (mac-algorithm hmac-sha256))
                              (error "Server signature missmatch!")))
               (session-nonce (scram-nonce 16)))

          (call-with-values (lambda ()
                              (aes-gcm-encrypt session-key session-nonce session-token))
            (lambda (cipher-text auth-tag)
              (let* ((session (create-session session-nonce transaction-id cipher-text auth-tag))
                     (refreshToken (assoc-ref session "refreshToken"))
                     (authToken (assoc-ref session "token")))
                (set! token (string->symbol authToken)))))))
      (lambda ()
        (thunk token))
      (lambda () #f))))

(define (get-field data module field)
  (let ((module-value (assoc-ref (car (filter (lambda (elem) (string=? module (assoc-ref elem "moduleid"))) (vector->list data)))
                                  "processdata")))
    (assoc-ref (car (filter (lambda (elem) (string=? field (assoc-ref elem "id"))) (vector->list module-value)))
               "value")))

(define (storedata handle data)
  (let ((home-p (get-field data "devices:local" "Home_P")))
    (dbi-query handle (format #f "insert into plenticore (home_p) values (~s)" home-p))))

(define *process-args* #((("moduleid" . "devices:local")
                          ("processdataids" . #("Home_P" "HomePv_P" "HomeBat_P" "HomeGrid_P" "EM_State" "DigitalIn" "LimitEvuAbs")))
                         (("moduleid" . "devices:local:pv1")
                          ("processdataids" . #("P" "I" "U")))
                         (("moduleid" . "devices:local:pv2")
                          ("processdataids" . #("P" "I" "U")))
                         (("moduleid" . "devices:local:ac")
                          ("processdataids" . #("P" "Frequency" "CosPhi" "L1_U" "L1_I" "L1_P" "L2_U" "L2_I" "L2_P" "L3_U" "L3_I" "L3_P")))
                         (("moduleid" . "devices:local:battery")
                          ("processdataids" . #("P" "I" "U" "SoC" "Cycles")))))

(define (processdata token handle)
  (call-with-values (lambda ()
                      (http-post (build-uri 'http #:host *host* #:path *processdata*)
                                 #:headers `((content-type application/json (charset . "utf-8"))
                                             (accept (application/json))
                                             (accept-encoding (1000 . "gzip") (1000 . "deflate"))
                                             (authorization . (bearer ,token)))
                                 #:body (scm->json-string *process-args*)))
    (lambda (res body)
      (let ((data (json-string->scm (ensure-string body))))
        (storedata handle data)))))

(define (with-dbi-handle cfg thunk)
  (let ((handle #f))
    (dynamic-wind
      (lambda ()
        (set! handle (dbi-open "postgresql" (assoc-ref cfg "connection"))))
      (lambda ()
        (thunk handle))
      (lambda ()
        (dbi-close handle)))))

(define (init handle)
  (dbi-query handle "create table if not exists plenticore (
home_p double precision
)"))

(define (observe cfg)
  (with-rfc5802-auth (assoc-ref cfg "password")
                     (lambda (token)
                       (with-dbi-handle cfg (lambda (handle)
                                              (init handle)
                                              (let loop ()
                                                (processdata token handle)
                                                (sleep 10)
                                                (loop)))))))
