{
 "title": "Kostal Plenticore",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Power Distribution",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "dataset": "fb",
     "rawSql": "select time, iv_p as \"Total\", grid_p as \"Grid\", home_p as \"Home\", bat_p as \"Battery\"\nfrom plenticore "
    }
   ]
  },
  {
   "title": "PV Power",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "dataset": "fb",
     "rawSql": "select time, pv1_p as \"PV West\", pv2_p as \"PV East\"\nfrom plenticore "
    }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "fb",
     "rawSql": "select bat_soc\nfrom plenticore\norder by time"
    }
   ]
  },
  {
   "title": "Battery Cycle",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "fb",
     "rawSql": "select bat_cycles\nfrom plenticore\norder by time"
    }
   ]
  },
  {
   "title": "Battery Charge History",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "fb",
     "rawSql": "select time, bat_soc as \"Charge\"\nfrom plenticore "
    }
   ]
  },
  {
   "title": "Home Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "dataset": "fb",
     "rawSql": "select time, home_p as \"Total Power\", home_p_bat as \"Battery\", home_p_grid as \"Grid\", home_p_pv as \"PV\"\nfrom plenticore"
    }
   ]
  }
 ]
}